### ISSUE TITLE
Allow set width/height of iron-image?

### ISSUE THREAD

**Issue by diegohaz** [PolymerElements/paper-card#50] opened 2015-12-17 06:07 UTC
I'm making a Pinterest-like grid (paper-cards with variable heights). I get the images urls from a database and have its dimensions. But, as I'm not able to change iron-image directly, I can't set the dimensions.

If the images aren't cached by the browser, it makes the page to break, because the grid structure is calculated by Javascript using `clientWidth` and `clientHeight` of each item (in this case, paper-card).

I don't know if there's another way to do that as simple as adding `imageWidth` and `imageHeight` properties to paper-card.

I can make a PR later today. :blush:

**Comment by bicknellr** [comment] 2015-12-19 00:09
@diegohaz You can use the [`--paper-card-header-image`](https://github.com/PolymerElements/paper-card/blob/b113ef10a581053d5e4842de154649a3482aa333/paper-card.html#L90) mixin to apply css to the wrapped `iron-image`.

**Comment by diegohaz** [comment] 2015-12-19 00:12
@bicknellr I see, but how can I handle multiple paper-cards with different sizes?

**Comment by bicknellr** [comment] 2015-12-19 01:30
Well, you can set `--paper-card-header-image` on each card with the `customStyle` property but that requires some lame string building since it's a mixin and might become a hassle to keep in sync. If you're wrapping the cards in another element that gets passed some single image data object, the syncing issue becomes pretty simple though. (This isn't a great solution though..)

I think you should consider putting your own `iron-image` in the paper-card (without any `card-*` classes) rather than trying to use the built-in header image. The implemenation of `paper-card` will show you how to get the same initial layout, which you can then tweak to your specific needs.

**Comment by notwaldorf** [comment] 2016-01-30 01:26
Closing, as this was answered. I don't think `paper-card` was designed for this. You can use the mixin perhaps by applying unique classes to each of your cards:
```
paper-card.class1 {
  --paper-card-header-image: {...};
}
paper-card.class2 {
  --paper-card-header-image: {...};
}
...
```

or do what @bicknellr suggested and use your own image (rather than the built in one)

**Closed by notwaldorf** 2016-01-30 01:26 UTC
