### ISSUE TITLE
Problem with horizontal align

### ISSUE THREAD

**Issue by vashchenkov** [PolymerElements/paper-card#47] opened 2015-12-03 11:33 UTC
I use version "1.0.8".
And insert paper-card element and activate developers tools i can see 

two blocs of paper card style

===================
paper-card {
        display: block;
        position: relative;
}

paper-card {
        display: inline-block;
        position: relative;
        box-sizing: border-box;
        background: #fff;
        border-radius: 2px;
}

===================
And last display style block is overwrite "display:block" and this prevent to align card in center
P.S. I use theme "technology"

**Comment by notwaldorf** [comment] 2015-12-09 01:15
I'm sorry, I don't exactly understand what you're doing, nor what you're trying to achieve. Are those CSS styles something that you've defined? I don't see any horizontal alignment that you're trying to use either.

Here's a sample jsbin (http://jsbin.com/yutagi/edit?html,output). Please clone it and try to reproduce your issue there, otherwise there isn't much I can go on with here :(

**Comment by notwaldorf** [comment] 2015-12-16 00:03
Closing this, since there's no answer. Please open a new issue with proper repro steps if there's still a bug.

**Closed by notwaldorf** 2015-12-16 00:03 UTC
Labels: pending-response
